# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ai_prompt.ui'
#
# Created by: PyQt6 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AiPromptPanel(object):
    def setupUi(self, AiPromptPanel):
        AiPromptPanel.setObjectName("AiPromptPanel")
        AiPromptPanel.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(AiPromptPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputArea = QtWidgets.QPlainTextEdit(AiPromptPanel)
        self.outputArea.setObjectName("outputArea")
        self.verticalLayout.addWidget(self.outputArea)
        self.submitBtn = QtWidgets.QPushButton(AiPromptPanel)
        self.submitBtn.setObjectName("submitBtn")
        self.verticalLayout.addWidget(self.submitBtn)

        self.retranslateUi(AiPromptPanel)
        QtCore.QMetaObject.connectSlotsByName(AiPromptPanel)

    def retranslateUi(self, AiPromptPanel):
        _translate = QtCore.QCoreApplication.translate
        AiPromptPanel.setWindowTitle(_translate("AiPromptPanel", "AI Prompt Input Panel"))
        self.submitBtn.setText(_translate("AiPromptPanel", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AiPromptPanel = QtWidgets.QWidget()
    ui = Ui_AiPromptPanel()
    ui.setupUi(AiPromptPanel)
    AiPromptPanel.show()
    sys.exit(app.exec_())
